name: fl_line_chart_example
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0

  fl_chart: ^0.12.0
  carousel_slider: ^4.0.0
  flutter_settings_screens: ^0.2.2+1
  font_awesome_flutter: ^9.2.0
  http: ^0.13.4
  art_sweetalert: ^0.0.5
  google_fonts: ^2.2.0
  settings_ui: ^2.0.2
  flutter_vector_icons: ^1.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true